module.exports = function () {
	return {
		'pro-solid-svg-icons': [
			'home',
			'code',
			'file-lines',
			'folder',
			'folders',
			'folder-tree',
			'typewriter',
			'link',
			'map-marker',
			'lightbulb',
			'lightbulb-on',
			'phone',
			'envelope',
			'globe',
			'print',
		],
		'pro-duotone-svg-icons': [
			'home',
			'code',
			'file-lines',
			'folder',
			'folders',
			'folder-tree',
			'typewriter',
			'link',
			'map-marker',
			'lightbulb',
			'lightbulb-on',
			'phone',
			'envelope',
			'globe',
			'print',
		],
		'free-brands-svg-icons': [
			'github',
			'twitter',
			'twitch',
			'youtube',
			'instagram',
			'tiktok',
			'facebook',
			'linkedin',
			'deviantart',
			'apple',
			'android',
		],
	};
};
